# Generated by Django 5.1.2 on 2024-11-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stockdata_is_complete_stockdata_remain_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='order_type',
            field=models.CharField(default='00', max_length=5),
        ),
    ]
