# Generated by Django 5.1.2 on 2024-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stockdata_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='cancel_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='real_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='real_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='target_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='order_type',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
